export const medicalJobs = [
    'personal care attendant - medical',
    'personal care provider - home care',
    'personal support worker - home support',
    'child care provider - private home',
    'health care aide',
    'child caregiver - private home',
    'home child care provider',
    'home health care worker',
    'home support worker',
    'home-care worker',
    'family caregiver',
    'family child care provider',
    'daycare aide',
    'daycare helper',
    'medical office assistant',
    'medical administrative assistant',
    "parent's helper",
    'pharmacy aide',
    'pharmacy helper',
];

export const generalJobs = [
    'sales associate',
    'beauty salon attendant',
    'beauty salon receptionist',
    'hairstylist',
    'bakery assistant - food store',
    'bakery labourer',
    'dishwasher',
    'cashier',
    'cashier, supermarket',
    'home cleaner',
    'cleaner',
    'cleaner, light duty',
    "cook's helper, kitchen helper",
    'server - food and beverage services',
    'farm labourer',
    'farm labourer - harvesting',
    'farm worker',
    'farm worker - harvesting',
    'farm worker, fruit',
    'farm worker, general',
    'farm worker, grain',
    'farm worker, vegetables',
    'food and beverage server',
    'food and beverage services attendant',
    'food counter attendant',
    'food service counter attendant',
    'food service helper',
    'fruit farm labourer',
    'fruit farm worker',
    'general farm worker',
    'general farm worker - harvesting',
    'general labourer - farm',
    'grain farm worker',
    'harvesting labourer',
    'hotel cleaner',
    'housekeeping aide',
    'housekeeping attendant',
    'housekeeping room attendant',
    'light duty cleaner',
    'mushroom farm worker',
    'receptionist',
    'worker, farm',
];
